using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace _3.Model
{
    public static class SuggestionDataSource
    {
        private static List<Contact> _Contacts = new List<Contact>
        {
            new Contact("James", "Buchanan", "Benton"),
            new Contact("Josephine", "Darakjy", "Chanay"),
            new Contact("Art", "Venere", "Chemel"),
            new Contact("Lenna", "Paprocki", "Feltz Printing Service"),
            new Contact("Donette", "Foller", "Printing Dimensions"),
            new Contact("Simona", "Morasca", "Chapman"),
            new Contact("Mitsue", "Tollner", "Morlong Associates"),
            new Contact("Leota", "Dilliard", "Commercial Press"),
            new Contact("Sage", "Wieser", "Truhlar And Truhlar Attys"),
            new Contact("Kris", "Marrier", "King"),
            new Contact("Minna", "Amigon", "Dorl"),
            new Contact("Abel", "Maclead", "Rangoni Of Florence"),
            new Contact("Kiley", "Caldarera", "Feiner Bros"),
            new Contact("Graciela", "Ruta", "Buckley Miller & Wright"),
            new Contact("Cammy", "Albares", "Rousseaux"),
            new Contact("Mattie", "Poquette", "Century Communications"),
            new Contact("Meaghan", "Garufi", "Bolton"),
            new Contact("Gladys", "Rim", "T M Byxbee Company Pc"),
            new Contact("Yuki", "Whobrey", "Farmers Insurance Group"),
            new Contact("Fletcher", "Flosi", "Post Box Services Plus"),
            new Contact("Bette", "Nicka", "Sport En Art"),
            new Contact("Veronika", "Inouye", "C 4 Network Inc"),
            new Contact("Willard", "Kolmetz", "Ingalls"),
            new Contact("Maryann", "Royster", "Franklin"),
            new Contact("Alisha", "Slusarski", "Wtlz Power 107 Fm"),
            new Contact("Allene", "Iturbide", "Ledecky"),
            new Contact("Chanel", "Caudy", "Professional Image Inc"),
            new Contact("Ezekiel", "Chui", "Sider"),
            new Contact("Willow", "Kusko", "U Pull It"),
            new Contact("Bernardo", "Figeroa", "Clark"),
            new Contact("Ammie", "Corrio", "Moskowitz"),
            new Contact("Francine", "Vocelka", "Cascade Realty Advisors Inc"),
            new Contact("Ernie", "Stenseth", "Knwz Newsradio"),
            new Contact("Albina", "Glick", "Giampetro"),
            new Contact("Alishia", "Sergi", "Milford Enterprises Inc"),
            new Contact("Solange", "Shinko", "Mosocco"),
            new Contact("Jose", "Stockham", "Tri State Refueler Co"),
            new Contact("Rozella", "Ostrosky", "Parkway Company"),
            new Contact("Valentine", "Gillian", "Fbs Business Finance"),
            new Contact("Kati", "Rulapaugh", "Eder Assocs Consltng Engrs Pc"),
            new Contact("Youlanda", "Schemmer", "Tri M Tool Inc"),
            new Contact("Dyan", "Oldroyd", "International Eyelets Inc"),
            new Contact("Roxane", "Campain", "Rapid Trading Intl"),
            new Contact("Lavera", "Perin", "Abc Enterprises Inc"),
            new Contact("Erick", "Ferencz", "Cindy Turner Associates"),
            new Contact("Fatima", "Saylors", "Stanton"),
            new Contact("Jina", "Briddick", "Grace Pastries Inc"),
            new Contact("Kanisha", "Waycott", "Schroer"),
            new Contact("Emerson", "Bowley", "Knights Inn"),
            new Contact("Blair", "Malet", "Bollinger Mach Shp & Shipyard"),
            new Contact("Brock", "Bolognia", "Orinda News"),
            new Contact("Lorrie", "Nestle", "Ballard Spahr Andrews"),
            new Contact("Sabra", "Uyetake", "Lowy Limousine Service"),
            new Contact("Marjory", "Mastella", "Vicon Corporation"),
            new Contact("Karl", "Klonowski", "Rossi"),
            new Contact("Tonette", "Wenner", "Northwest Publishing"),
            new Contact("Amber", "Monarrez", "Branford Wire & Mfg Co"),
            new Contact("Shenika", "Seewald", "East Coast Marketing"),
            new Contact("Delmy", "Ahle", "Wye Technologies Inc"),
            new Contact("Deeanna", "Juhas", "Healy"),
            new Contact("Blondell", "Pugh", "Alpenlite Inc"),
            new Contact("Jamal", "Vanausdal", "Hubbard"),
            new Contact("Cecily", "Hollack", "Arthur A Oliver & Son Inc"),
            new Contact("Carmelina", "Lindall", "George Jessop Carter Jewelers"),
            new Contact("Maurine", "Yglesias", "Schultz"),
            new Contact("Tawna", "Buvens", "H H H Enterprises Inc"),
            new Contact("Penney", "Weight", "Hawaiian King Hotel"),
            new Contact("Elly", "Morocco", "Killion Industries"),
            new Contact("Ilene", "Eroman", "Robinson"),
            new Contact("Vallie", "Mondella", "Private Properties"),
            new Contact("Kallie", "Blackwood", "Rowley Schlimgen Inc"),
            new Contact("Johnetta", "Abdallah", "Forging Specialties"),
            new Contact("Bobbye", "Rhym", "Smits"),
            new Contact("Micaela", "Rhymes", "H Lee Leonard Attorney At Law"),
            new Contact("Tamar", "Hoogland", "A K Construction Co"),
            new Contact("Moon", "Parlato", "Ambelang"),
            new Contact("Laurel", "Reitler", "Q A Service"),
            new Contact("Delisa", "Crupi", "Wood & Whitacre Contractors"),
            new Contact("Viva", "Toelkes", "Mark Iv Press Ltd"),
            new Contact("Elza", "Lipke", "Museum Of Science & Industry"),
            new Contact("Devorah", "Chickering", "Garrison Ind"),
            new Contact("Timothy", "Mulqueen", "Saronix Nymph Products"),
            new Contact("Arlette", "Honeywell", "Smc Inc"),
            new Contact("Dominque", "Dickerson", "E A I Electronic Assocs Inc"),
            new Contact("Lettie", "Isenhower", "Conte"),
            new Contact("Myra", "Munns", "Anker Law Office"),
            new Contact("Stephaine", "Barfield", "Beutelschies & Company"),
            new Contact("Lai", "Gato", "Fligg"),
            new Contact("Stephen", "Emigh", "Sharp"),
            new Contact("Tyra", "Shields", "Assink"),
            new Contact("Tammara", "Wardrip", "Jewel My Shop Inc"),
            new Contact("Cory", "Gibes", "Chinese Translation Resources"),
            new Contact("Danica", "Bruschke", "Stevens"),
            new Contact("Wilda", "Giguere", "Mclaughlin"),
            new Contact("Elvera", "Benimadho", "Tree Musketeers"),
            new Contact("Carma", "Vanheusen", "Springfield Div Oh Edison Co"),
            new Contact("Malinda", "Hochard", "Logan Memorial Hospital"),
            new Contact("Natalie", "Fern", "Kelly"),
            new Contact("Lisha", "Centini", "Industrial Paper Shredders Inc"),
            new Contact("Arlene", "Klusman", "Beck Horizon Builders"),
            new Contact("Alease", "Buemi", "Porto Cayo At Hawks Cay"),
            new Contact("Louisa", "Cronauer", "Pacific Grove Museum Ntrl Hist"),
            new Contact("Angella", "Cetta", "Bender & Hatley Pc"),
            new Contact("Cyndy", "Goldammer", "Di Cristina J & Son"),
            new Contact("Rosio", "Cork", "Green Goddess"),
            new Contact("Celeste", "Korando", "American Arts & Graphics"),
            new Contact("Twana", "Felger", "Opryland Hotel"),
            new Contact("Estrella", "Samu", "Marking Devices Pubg Co"),
            new Contact("Donte", "Kines", "W Tc Industries Inc"),
            new Contact("Tiffiny", "Steffensmeier", "Whitehall Robbins Labs Divsn"),
            new Contact("Edna", "Miceli", "Sampler"),
            new Contact("Sue", "Kownacki", "Juno Chefs Incorporated"),
            new Contact("Jesusa", "Shin", "Carroccio"),
            new Contact("Rolland", "Francescon", "Stanley"),
            new Contact("Pamella", "Schmierer", "K Cs Cstm Mouldings Windows"),
            new Contact("Glory", "Kulzer", "Comfort Inn"),
            new Contact("Shawna", "Palaspas", "Windsor"),
            new Contact("Brandon", "Callaro", "Jackson Shields Yeiser"),
            new Contact("Scarlet", "Cartan", "Box"),
            new Contact("Oretha", "Menter", "Custom Engineering Inc"),
            new Contact("Ty", "Smith", "Bresler Eitel Framg Gllry Ltd"),
            new Contact("Xuan", "Rochin", "Carol"),
            new Contact("Lindsey", "Dilello", "Biltmore Investors Bank"),
            new Contact("Devora", "Perez", "Desco Equipment Corp"),
            new Contact("Herman", "Demesa", "Merlin Electric Co"),
            new Contact("Rory", "Papasergi", "Bailey Cntl Co Div Babcock"),
            new Contact("Talia", "Riopelle", "Ford Brothers Wholesale Inc"),
            new Contact("Van", "Shire", "Cambridge Inn"),
            new Contact("Lucina", "Lary", "Matricciani"),
            new Contact("Bok", "Isaacs", "Nelson Hawaiian Ltd"),
            new Contact("Rolande", "Spickerman", "Neland Travel Agency"),
            new Contact("Howard", "Paulas", "Asendorf"),
            new Contact("Kimbery", "Madarang", "Silberman"),
            new Contact("Thurman", "Manno", "Honey Bee Breeding Genetics &"),
            new Contact("Becky", "Mirafuentes", "Wells Kravitz Schnitzer"),
            new Contact("Beatriz", "Corrington", "Prohab Rehabilitation Servs"),
            new Contact("Marti", "Maybury", "Eldridge"),
            new Contact("Nieves", "Gotter", "Vlahos"),
            new Contact("Leatha", "Hagele", "Ninas Indian Grs & Videos"),
            new Contact("Valentin", "Klimek", "Schmid"),
            new Contact("Melissa", "Wiklund", "Moapa Valley Federal Credit Un"),
            new Contact("Sheridan", "Zane", "Kentucky Tennessee Clay Co"),
            new Contact("Bulah", "Padilla", "Admiral Party Rentals & Sales"),
            new Contact("Audra", "Kohnert", "Nelson"),
            new Contact("Daren", "Weirather", "Panasystems"),
            new Contact("Fernanda", "Jillson", "Shank"),
            new Contact("Gearldine", "Gellinger", "Megibow & Edwards"),
            new Contact("Chau", "Kitzman", "Benoff"),
            new Contact("Theola", "Frey", "Woodbridge Free Public Library"),
            new Contact("Cheryl", "Haroldson", "New York Life John Thune"),
            new Contact("Laticia", "Merced", "Alinabal Inc"),
            new Contact("Carissa", "Batman", "Poletto"),
            new Contact("Lezlie", "Craghead", "Chang"),
            new Contact("Ozell", "Shealy", "Silver Bros Inc"),
            new Contact("Arminda", "Parvis", "Newtec Inc"),
            new Contact("Reita", "Leto", "Creative Business Systems"),
            new Contact("Yolando", "Luczki", "Dal Tile Corporation"),
            new Contact("Lizette", "Stem", "Edward S Katz"),
            new Contact("Gregoria", "Pawlowicz", "Oh My Goodknits Inc"),
            new Contact("Carin", "Deleo", "Redeker"),
            new Contact("Chantell", "Maynerich", "Desert Sands Motel"),
            new Contact("Dierdre", "Yum", "Cummins Southern Plains Inc"),
            new Contact("Larae", "Gudroe", "Lehigh Furn Divsn Lehigh"),
            new Contact("Latrice", "Tolfree", "United Van Lines Agent"),
            new Contact("Kerry", "Theodorov", "Capitol Reporters"),
            new Contact("Dorthy", "Hidvegi", "Kwik Kopy Printing"),
            new Contact("Fannie", "Lungren", "Centro Inc"),
            new Contact("Evangelina", "Radde", "Campbell"),
            new Contact("Novella", "Degroot", "Evans"),
            new Contact("Clay", "Hoa", "Scat Enterprises"),
            new Contact("Jennifer", "Fallick", "Nagle"),
            new Contact("Irma", "Wolfgramm", "Serendiquity Bed & Breakfast"),
            new Contact("Eun", "Coody", "Ray Carolyne Realty"),
            new Contact("Sylvia", "Cousey", "Berg"),
            new Contact("Nana", "Wrinkles", "Ray"),
            new Contact("Layla", "Springe", "Chadds Ford Winery"),
            new Contact("Joesph", "Degonia", "A R Packaging"),
            new Contact("Annabelle", "Boord", "Corn Popper"),
            new Contact("Stephaine", "Vinning", "Birite Foodservice Distr"),
            new Contact("Nelida", "Sawchuk", "Anchorage Museum Of Hist & Art"),
            new Contact("Marguerita", "Hiatt", "Haber"),
            new Contact("Carmela", "Cookey", "Royal Pontiac Olds Inc"),
            new Contact("Junita", "Brideau", "Leonards Antiques Inc"),
            new Contact("Claribel", "Varriano", "Meca"),
            new Contact("Benton", "Skursky", "Nercon Engineering & Mfg Inc"),
            new Contact("Hillary", "Skulski", "Replica I"),
            new Contact("Merilyn", "Bayless", "20 20 Printing Inc"),
            new Contact("Teri", "Ennaco", "Publishers Group West"),
            new Contact("Merlyn", "Lawler", "Nischwitz"),
            new Contact("Georgene", "Montezuma", "Payne Blades & Wellborn Pa"),
            new Contact("Jettie", "Mconnell", "Coldwell Bnkr Wright Real Est"),
            new Contact("Lemuel", "Latzke", "Computer Repair Service"),
            new Contact("Melodie", "Knipp", "Fleetwood Building Block Inc"),
            new Contact("Candida", "Corbley", "Colts Neck Medical Assocs Inc"),
            new Contact("Karan", "Karpin", "New England Taxidermy"),
            new Contact("Andra", "Scheyer", "Ludcke"),
            new Contact("Felicidad", "Poullion", "Mccorkle"),
            new Contact("Belen", "Strassner", "Eagle Software Inc"),
            new Contact("Gracia", "Melnyk", "Juvenile & Adult Super"),
            new Contact("Jolanda", "Hanafan", "Perez"),
            new Contact("Barrett", "Toyama", "Case Foundation Co"),
            new Contact("Helga", "Fredicks", "Eis Environmental Engrs Inc"),
            new Contact("Ashlyn", "Pinilla", "Art Crafters"),
            new Contact("Fausto", "Agramonte", "Marriott Hotels Resorts Suites"),
            new Contact("Ronny", "Caiafa", "Remaco Inc"),
            new Contact("Marge", "Limmel", "Bjork"),
            new Contact("Norah", "Waymire", "Carmichael"),
            new Contact("Aliza", "Baltimore", "Andrews"),
            new Contact("Mozell", "Pelkowski", "Winship & Byrne"),
            new Contact("Viola", "Bitsuie", "Burton & Davis"),
            new Contact("Franklyn", "Emard", "Olympic Graphic Arts"),
            new Contact("Willodean", "Konopacki", "Magnuson"),
            new Contact("Beckie", "Silvestrini", "A All American Travel Inc"),
            new Contact("Rebecka", "Gesick", "Polykote Inc"),
            new Contact("Frederica", "Blunk", "Jets Cybernetics"),
            new Contact("Glen", "Bartolet", "Metlab Testing Services"),
            new Contact("Freeman", "Gochal", "Kellermann"),
            new Contact("Vincent", "Meinerding", "Arturi"),
            new Contact("Rima", "Bevelacqua", "Mcauley Mfg Co"),
            new Contact("Glendora", "Sarbacher", "Defur Voran Hanley Radcliff"),
            new Contact("Avery", "Steier", "Dill Dill Carr & Stonbraker Pc"),
            new Contact("Cristy", "Lother", "Kleensteel"),
            new Contact("Nicolette", "Brossart", "Goulds Pumps Inc Slurry Pump"),
            new Contact("Tracey", "Modzelewski", "Kansas City Insurance Report"),
            new Contact("Virgina", "Tegarden", "Berhanu International Foods"),
            new Contact("Tiera", "Frankel", "Roland Ashcroft"),
            new Contact("Alaine", "Bergesen", "Hispanic Magazine"),
            new Contact("Earleen", "Mai", "Little Sheet Metal Co"),
            new Contact("Leonida", "Gobern", "Holmes"),
            new Contact("Ressie", "Auffrey", "Faw"),
            new Contact("Justine", "Mugnolo", "Evans Rule Company"),
            new Contact("Eladia", "Saulter", "Tyee Productions Inc"),
            new Contact("Chaya", "Malvin", "Dunnells & Duvall"),
            new Contact("Gwenn", "Suffield", "Deltam Systems Inc"),
            new Contact("Salena", "Karpel", "Hammill Mfg Co"),
            new Contact("Yoko", "Fishburne", "Sams Corner Store"),
            new Contact("Taryn", "Moyd", "Siskin"),
            new Contact("Katina", "Polidori", "Cape & Associates Real Estate"),
            new Contact("Rickie", "Plumer", "Merrill Lynch"),
            new Contact("Alex", "Loader", "Sublett"),
            new Contact("Lashon", "Vizarro", "Sentry Signs"),
            new Contact("Lauran", "Burnard", "Professionals Unlimited"),
            new Contact("Ceola", "Setter", "Southern Steel Shelving Co"),
            new Contact("My", "Rantanen", "Bosco"),
            new Contact("Lorrine", "Worlds", "Longo"),
            new Contact("Peggie", "Sturiale", "Henry County Middle School"),
            new Contact("Marvel", "Raymo", "Edison Supply & Equipment Co"),
            new Contact("Daron", "Dinos", "Wolf"),
            new Contact("An", "Fritz", "Linguistic Systems Inc"),
            new Contact("Portia", "Stimmel", "Peace Christian Center"),
            new Contact("Rhea", "Aredondo", "Double B Foods Inc"),
            new Contact("Benedict", "Sama", "Alexander & Alexander Inc"),
            new Contact("Alyce", "Arias", "Fairbanks Scales"),
            new Contact("Heike", "Berganza", "Cali Sportswear Cutting Dept"),
            new Contact("Carey", "Dopico", "Garofani"),
            new Contact("Dottie", "Hellickson", "Thompson Fabricating Co")
        }.OrderBy(c => c.FullName).ToList();
        public static List<Contact> Contacts
        {
            get
            {
                return _Contacts;
            }
        }
        public static IEnumerable<Contact> GetSuggestionContact(string query)
        {
            return SuggestionDataSource.Contacts
                .Where(c => c.FirstName.IndexOf(query, StringComparison.CurrentCultureIgnoreCase) > -1 ||
                            c.LastName.IndexOf(query, StringComparison.CurrentCultureIgnoreCase) > -1 ||
                            c.Company.IndexOf(query, StringComparison.CurrentCultureIgnoreCase) > -1)
                .OrderByDescending(c => c.FirstName.StartsWith(query, StringComparison.CurrentCultureIgnoreCase))
                .ThenByDescending(c => c.LastName.StartsWith(query, StringComparison.CurrentCultureIgnoreCase))
                .ThenByDescending(c => c.Company.StartsWith(query, StringComparison.CurrentCultureIgnoreCase));
        }
    }
}
